#!/usr/bin/env bun

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const settingsPath = resolve(root, "pi/settings.json");
const outputPath = resolve(root, "docs/model-routing.md");
const settings = JSON.parse(readFileSync(settingsPath, "utf8"));
const overrides = settings?.subagents?.agentOverrides;

if (!overrides || Array.isArray(overrides) || typeof overrides !== "object") {
  throw new Error("pi/settings.json must define subagents.agentOverrides");
}

const roleMetadata = {
  scout: ["Local retrieval", "Workflow 1ce208b8: 3-line Luna read-only probe, no project writes", "2026-08-28"],
  researcher: ["Web research with citations", "Workflow 1ce208b8: Luna probe returned two cited findings", "2026-08-28"],
  worker: ["Implementation", "Workflow 1ce208b8: disposable /tmp writer created two-line PROBE.md", "2026-08-28"],
  "petey-agent": ["Petey-aware implementation and prose", "Workflow 1ce208b8: Grok Fast high read-only routing probe", "2026-08-28"],
  reviewer: ["Independent review, council counterpoint, and cross-judging", "Pending post-restart Grok xhigh role probe", "Pending"],
  "comment-sicko": ["Scoped comment deletion", "Pending post-restart Luna medium writer probe", "Pending"],
  oracle: ["Inherited-context judgment", "Workflow 1ce208b8: Sol xhigh forked one-shot PASS on PROBE.md", "2026-08-28"],
  "council-sol": ["Council and architecture judgment", "Workflow 1ce208b8: independent Sol xhigh accept on content", "2026-08-28"],
};

const expectedRoles = Object.keys(roleMetadata);
const missing = expectedRoles.filter((role) => !overrides[role]);
if (missing.length) throw new Error(`Missing routing overrides: ${missing.join(", ")}`);

function cell(value) {
  if (Array.isArray(value)) return value.length ? value.join("<br>") : "None";
  if (value === false) return "None";
  if (value === undefined || value === null || value === "") return "Inherit";
  return String(value).replaceAll("|", "\\|");
}

const rows = expectedRoles.map((role) => {
  const override = overrides[role];
  const [job, evidence, verified] = roleMetadata[role];
  return `| \`${role}\` | \`${cell(override.model)}\` | \`${cell(override.thinking)}\` | \`${cell(override.defaultContext)}\` | ${cell(override.fallbackModels)} | ${job} | ${evidence} | ${verified} |`;
});

const content = `# Model routing\n\nThis file is generated by \`bun run scripts/render-model-routing.ts\` from \`pi/settings.json\`. Edit the settings file, then regenerate this table. This document explains the live selector. It does not configure Pi.\n\n| Agent | Model | Thinking | Context | Fallback models | Intended job | Eval evidence | Last verified |\n| --- | --- | --- | --- | --- | --- | --- | --- |\n${rows.join("\n")}\n\n## Policy notes\n\n- The parent model and thinking level remain a session choice.\n- Fresh context needs a standalone brief. It does not isolate filesystem writes. One writer owns each checkout or worktree.\n- Implementation roles have no fallback. Provider failures must surface.\n- Native priority mode stays disabled until a supported provider selector passes a live probe.\n- Runtime verification remains pending after settings changes until Pi restarts and each role is probed.\n`;

if (process.argv.includes("--check")) {
  let current;
  try {
    current = readFileSync(outputPath, "utf8");
  } catch {
    console.error(`Missing generated file: ${outputPath}`);
    process.exit(1);
  }
  if (current !== content) {
    console.error(`Generated file is stale: ${outputPath}`);
    process.exit(1);
  }
  console.log(`Generated file is current: ${outputPath}`);
} else {
  writeFileSync(outputPath, content);
  console.log(`Wrote ${outputPath}`);
}
